name = "NeurobloxBasics"
uuid = "6341abd9-5539-449d-87b3-7e81c4d50fb5"
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphDynamics = "bcd5d0fe-e6b7-4ef1-9848-780c183c7f4c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeurobloxBase = "c1a47a78-a13f-4f42-9de5-c5b922306e53"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Accessors = "0.1.37"
DiffEqCallbacks = "4"
Distributions = "0.25.102"
GraphDynamics = "0.5"
Graphs = "1"
MetaGraphs = "0.7, 0.8"
ModelingToolkit = "<9.76"
NeurobloxBase = "0.1"
ProgressMeter = "1.10.4"
Random = "1.11.0"
RecursiveArrayTools = "2, 3"
Reexport = "1.0"
SciMLBase = "2.111.1"
SparseArrays = "1.11.0"
StatsBase = "0.34.6"
SymbolicUtils = "3.31.0"
Symbolics = "6.51.0"
julia = "1.10"

[workspace]
projects = ["test"]