name = "NeurobloxBase"
uuid = "c1a47a78-a13f-4f42-9de5-c5b922306e53"
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphDynamics = "bcd5d0fe-e6b7-4ef1-9848-780c183c7f4c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MakieExtension = ["Colors", "Makie"]

[compat]
Accessors = "0.1.37"
CairoMakie = ">=0.11"
Colors = ">=0.12"
DSP = "0.8"
DiffEqCallbacks = "4"
Distributions = "0.25.102"
GraphDynamics = "0.5"
Graphs = "1"
Interpolations = "0.16"
LinearAlgebra = "1.11"
Makie = ">=0.20"
MetaGraphs = "0.7, 0.8"
ModelingToolkit = "<9.76"
OhMyThreads = "0.8"
OrderedCollections = "1.8"
Peaks = "0.5"
Preferences = "1"
Random = "1.11.0"
RecursiveArrayTools = "2, 3"
Reexport = "1.0"
SciMLBase = "2.111.1"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.6"
SymbolicIndexingInterface = "0.3.43"
SymbolicUtils = "3.31.0"
Symbolics = "6.51.0"
Test = "1.11.0"
julia = "1.10"
