name = "NeurobloxBase"
uuid = "c1a47a78-a13f-4f42-9de5-c5b922306e53"
version = "0.2.0"

[workspace]
projects = ["test"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExproniconLite = "55351af7-c7e9-48d6-89ff-24e801d99491"
GraphDynamics = "bcd5d0fe-e6b7-4ef1-9848-780c183c7f4c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[sources]
GraphDynamics = {path = "../GraphDynamics"}

[extensions]
MakieExtension = ["Colors", "Makie"]
NBLatexifyExt = ["Symbolics", "Latexify"]

[compat]
Accessors = "0.1.37"
CairoMakie = ">=0.11"
Colors = ">=0.12"
DSP = "0.8"
DiffEqCallbacks = "4"
Distributions = "0.25.102"
ExproniconLite = "0.10.14"
GraphDynamics = "0.7"
Interpolations = "0.16"
JLD2 = "0.6.3"
Latexify = "0.16.10"
LinearAlgebra = "1.11"
MLStyle = "0.4.17"
Makie = ">=0.20"
OhMyThreads = "0.8"
OrderedCollections = "1.8"
Peaks = "0.5, 0.6"
Preferences = "1"
Random = "1.11.0"
RecursiveArrayTools = "2, 3"
Reexport = "1.0"
SciMLBase = "2.111.1"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.6"
SymbolicIndexingInterface = "0.3.43"
Symbolics = "6, 7"
julia = "1.10"
