name = "NeurobloxPharma"
uuid = "6d6291d7-c437-44bd-acf4-438a4f54bfaa"
version = "0.2.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphDynamics = "bcd5d0fe-e6b7-4ef1-9848-780c183c7f4c"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
NeurobloxBase = "c1a47a78-a13f-4f42-9de5-c5b922306e53"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[extensions]
UnicodePlotsExt = "UnicodePlots"

[compat]
Accessors = "0.1.37"
CSV = "0.10.15"
DataFrames = "1.3"
DiffEqCallbacks = "4"
Distributions = "0.25.102"
GraphDynamics = "0.7"
LogExpFunctions = "0.3.29"
NeurobloxBase = "0.2"
ProgressMeter = "1.10.4"
Random = "1.11.0"
RecursiveArrayTools = "2, 3"
Reexport = "1.0"
SciMLBase = "2.111.1"
SparseArrays = "1.11.0"
StatsBase = "0.34.6"
NaNMath = "1"
julia = "1.10"
UnicodePlots = "3"

[workspace]
projects = ["test"]
