name: CI_master_only
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - GraphDynamics/**
      - NeurobloxBase/**
      - NeurobloxBasics/**
      - NeurobloxPharma/**
      - .github/workflows/CI_master_only.yml

jobs:
  test_NeurobloxPharma2:
    runs-on: [self-hosted, CI]
    timeout-minutes: 1600
    strategy:
      matrix:
        include:
          - group: Full_CS_RL_Pipeline
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.12.2'
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: 'NeurobloxPharma'
      - name: Run tests
        run: julia --project=NeurobloxPharma -e 'using Pkg; Pkg.test("NeurobloxPharma"; julia_args=["-O3"])'
        env:
          JULIA_NUM_THREADS: 4
          GROUP: ${{ matrix.group }}
