name: CI_NeurobloxDBS
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - GraphDynamics/**
      - NeurobloxBase/**
      - NeurobloxDBS/**
      - .github/workflows/CI_NeurobloxDBS.yml
  push:
    branches:
      - master
    paths:
      - GraphDynamics/**
      - NeurobloxBase/**
      - NeurobloxDBS/**
      - .github/workflows/CI_NeurobloxDBS.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
  
jobs:
  test_NeurobloxDBS:
    runs-on: [self-hosted, CI]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.12.2'
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: 'NeurobloxDBS'
      - name: Run tests
        run: julia --project=NeurobloxDBS -e 'using Pkg; Pkg.test(; julia_args=["-O1"])'
        env:
          REFERENCE_TESTS_STAGING_PATH: '${{ github.workspace }}/NeurobloxDBS/test/plots-staging/'
      - name: Make PR if reference tests changed
        if: always()
        uses: ./.github/actions/create-update-pr
        with:
          github-token: ${{ github.token }}
          commit-message: 'Update generated images from CI'
          pr-title-prefix: 'Update reference images ${{ github.job }}'
          branch-prefix: 'update-images-${{ github.job }}'
          reference-path: 'NeurobloxDBS/test/plots/'
          reference-staging-path: 'NeurobloxDBS/test/plots-staging/'
